site_name: NWChem
site_description: NWChem Website
repo_url: https://github.com/nwchemgit/nwchem-wiki
site_url: https://nwchemgit.github.io
edit_uri: blob/master/
theme:
  name: material
  logo: assets/MS3logo.png
  font:
    text: Lato
  palette:
#    primary: light blue
#    accent: indigo
#    font: false
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight
    - search.share
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - tables
    - footnotes:
        SEPARATOR: _footnote_
#    - markdown_katex:
#         no_inline_svg: True
#         insert_fonts_css: True
#         macro-file: macros.tex
#    - pymdownx.arithmatex
#extra_javascript:
#  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - mdx_math:
        enable_dollar_delimiter: True
    - pymdownx.tilde
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
plugins:
  - search
  - alternate-link
nav:
      - 'NWChem Manual': Home.md
      - 'How to download and install NWChem':
          - Download.md
          - Compiling-NWChem.md
      - 'Introduction ':
          - Getting-Started.md
          - NWChem-Architecture.md
      - Quantum-Mechanical-Methods:
          - Hartree-Fock-Theory-for-Molecules.md
          - Density-Functional-Theory-for-Molecules.md
          - Excited-State-Calculations.md
          - RT-TDDFT.md
          - 'Plane-Wave Density Functional Theory': Plane-Wave-Density-Functional-Theory.md
          - TCE.md
          - MP2.md
          - CCSD.md
          - Multiconfiguration_SCF.md
          - 'Molecular GW': GW.md
      - Quantum Molecular Dynamics:
          - Plane-Wave-Density-Functional-Theory.md
          - Gaussian-Basis-AIMD.md
      - Hybrid Approaches:
          - COSMO-Solvation-Model.md
          - SMD-Model.md
          - VEM-Model.md
          - ONIOM.md
          - QMMM.md
          - Bq.md
          - 1D-RISM.md
      - Potential Energy Surface Analysis:
          - Geometry-Optimization.md
          - Hessians-and-Vibrational-Frequencies.md
          - Constraints.md
          - Nudged-Elastic-Band-and-Zero-Temperature-String-Methods.md
      - Other-Capabilities:
          - Electron-Transfer.md
          - Python.md
          - Quantum.md
          - VSCF.md
          - CCCA_method.md
          - Interface.md
      - 'NWChem Examples': Examples.md
      - Benchmarks.md
      - Known-Bugs.md
      - 'FAQ': FAQ.md
      - 'NWChem Tutorials': Tutorials.md
      - Forum.md
      - 'Archived Forum': Archived-Forum.md
      - 'EMSL Arrows': EMSL_Arrows.md
      - Software-supporting-NWChem.md
      - Supplementary-Information.md
      - 'Containers': Containers.md
