name: NWChem_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-7
          - gcc-8
      fail-fast: false
    env:
        CC: ${{ matrix.compiler }}
        MPI_IMPL: "openmpi"
        NWCHEM_MODULES: "nwdft driver solvation"
        USE_MPI: y
        BUILD_OPENBLAS: y
        BUILD_SCALAPACK: y
        BLAS_SIZE: 8
        SCALAPACK_SIZE: 8
    steps: 
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 40
      - name: build environment
        run: |
          lscpu
          pwd
          ls -lart
          ./travis/build_env.sh
      - name: compile
        run: |
          ./travis/compile_nwchem.sh
      - name: qa_test
        run: |
          ./travis/run_qas.sh
  



     
