name: NWChem website update
on:
  release:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout nwchem code
        uses: actions/checkout@v2
        with:
          fetch-depth: 40
          
      - name: Set up Python 3
        uses: actions/setup-python@v2
      
      - name: install mkdocs and plugins
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          pwd
          bash ./install_mkdocs.sh
          mkdocs -h || true
      - name: checkout wiki
        uses: actions/checkout@v2
        with:
          path: contrib/mkdocs/docs
          repository: nwchemgit/nwchem-wiki
          persist-credentials: false
          fetch-depth: 0
      - name: check wiki source
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          ls -lrt docs
      - name: checkout archived forum
        uses: actions/checkout@v2
        with:
          path: contrib/mkdocs/docs/archivedforum
          repository: nwchemgit/archivedforum
          persist-credentials: false
          fetch-depth: 0
      - name: check archiveforum source
        shell: bash
        working-directory: contrib/mkdocs/docs/
        run: |
          ls -lrt archivedforum
          mv archivedforum/Special_AWCforum .
      - name: build website
        shell: bash
        working-directory: contrib/mkdocs
        run: |
          MKDOCS_SERVE=B bash ./build_website.sh
          ls -lart || true
          ls -lart site/index.html || true
      - name: checkout website
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          path: contrib/mkdocs/docs/nwchemgit.github.io
          repository: nwchemgit/nwchemgit.github.io
